import sbtbuildinfo.ScalaFinalCaseObjectRenderer

lazy val check = taskKey[Unit]("checks this plugin")

lazy val root = (project in file(".")).
  enablePlugins(BuildInfoPlugin).
  settings(
    name := "helloworld",
    version := "0.1",
    scalaVersion := "2.12.7",
    TaskKey[Classpath]("someCp") := Seq(Attributed.blank(file("/tmp/f.txt"))),
    buildInfoKeys := Seq[BuildInfoKey](
      name,
      BuildInfoKey.map(version) { case (n, v) => "projectVersion" -> v.toDouble },
      scalaVersion,
      ivyXML,
      homepage,
      licenses,
      apiMappings,
      isSnapshot,
      "year" -> 2012,
      "sym" -> 'Foo,
      BuildInfoKey.action("buildTime") { 1234L },
      TaskKey[Classpath]("someCp"),
      target),
    buildInfoOptions += BuildInfoOption.Traits("traits.MyCustomTrait"),
    buildInfoRenderFactory := ScalaFinalCaseObjectRenderer.apply,
    buildInfoPackage := "hello",
    homepage := Some(url("http://example.com")),
    licenses := Seq("MIT License" -> url("https://github.com/sbt/sbt-buildinfo/blob/master/LICENSE")),
    scalacOptions ++= Seq("-Ywarn-unused-import", "-Xfatal-warnings", "-Yno-imports"),
    libraryDependencies += "org.scala-lang.modules" %% "scala-xml" % "1.0.5",
    check := {
      val f = (sourceManaged in Compile).value / "sbt-buildinfo" / ("%s.scala" format "BuildInfo")
      val lines = scala.io.Source.fromFile(f).getLines.toList
      lines match {
        case """// $COVERAGE-OFF$""" ::
          """package hello""" ::
          """""" ::
          """import scala.Predef._""" ::
          """""" ::
          """/** This object was generated by sbt-buildinfo. */""" ::
          """case object BuildInfo extends traits.MyCustomTrait {""" ::
          """  /** The value is "helloworld". */"""::
          """  final val name: String = "helloworld"""" ::
          """  /** The value is 0.1. */"""::
          """  final val projectVersion = 0.1""" ::
          """  /** The value is "2.12.7". */""" ::
          """  final val scalaVersion: String = "2.12.7"""" ::
          """  /** The value is scala.collection.immutable.Seq(). */""" ::
          """  final val ivyXML: scala.xml.NodeSeq = scala.collection.immutable.Seq()""" ::
          """  /** The value is scala.Some(new java.net.URL("http://example.com")). */""" ::
          """  final val homepage: scala.Option[java.net.URL] = scala.Some(new java.net.URL("http://example.com"))""" ::
          """  /** The value is scala.collection.immutable.Seq(("MIT License" -> new java.net.URL("https://github.com/sbt/sbt-buildinfo/blob/master/LICENSE"))). */""" ::
          """  final val licenses: scala.collection.immutable.Seq[(String, java.net.URL)] = scala.collection.immutable.Seq(("MIT License" -> new java.net.URL("https://github.com/sbt/sbt-buildinfo/blob/master/LICENSE")))""" ::
          """  /** The value is Map(). */""" ::
          """  final val apiMappings: Map[java.io.File, java.net.URL] = Map()""" ::
          """  /** The value is false. */""" ::
          """  final val isSnapshot: scala.Boolean = false""" ::
          """  /** The value is 2012. */""" ::
          """  final val year: scala.Int = 2012""" ::
          """  /** The value is 'Foo. */""" ::
          """  final val sym: scala.Symbol = 'Foo""" ::
          """  /** The value is 1234L. */""" ::
          """  final val buildTime: scala.Long = 1234L""" ::
          """  /** The value is scala.collection.immutable.Seq(new java.io.File("/tmp/f.txt")). */""" ::
          """  final val someCp: scala.collection.immutable.Seq[java.io.File] = scala.collection.immutable.Seq(new java.io.File("/tmp/f.txt"))""" ::
          targetInfoComment ::
          targetInfo :: // """
          """  override val toString: String = {""" ::
          """    "name: %s, projectVersion: %s, scalaVersion: %s, ivyXML: %s, homepage: %s, licenses: %s, apiMappings: %s, isSnapshot: %s, year: %s, sym: %s, buildTime: %s, someCp: %s, target: %s".format(""" ::
          """      name, projectVersion, scalaVersion, ivyXML, homepage, licenses, apiMappings, isSnapshot, year, sym, buildTime, someCp, target""" ::
          """    )""" ::
          """  }""" ::
          """}""" ::
          """// $COVERAGE-ON$""" :: Nil  if targetInfo contains "target: java.io.File = new java.io.File(" =>
        case _ => sys.error("unexpected output: \n" + lines.mkString("\n"))
      }
      ()
    }
  )
