lazy val check = taskKey[Unit]("checks this plugin")

ThisBuild / version := "0.1"
ThisBuild / scalaVersion := "2.12.12"

lazy val root = (project in file("."))
  .enablePlugins(BuildInfoPlugin)
  .settings(
    name := "helloworld",
    buildInfoKeys := Seq(
      name,
      scalaVersion,
    ),
    buildInfoPackage := "hello",
    buildInfoOptions ++= Seq(
      BuildInfoOption.ToJson,
      BuildInfoOption.ToMap,
      BuildInfoOption.Traits("TestTrait1", "TestTrait2"),
      BuildInfoOption.Traits("TestTrait3"),
      BuildInfoOption.PackagePrivate),
    homepage := Some(url("http://example.com")),
    licenses := Seq("MIT License" -> url("https://github.com/sbt/sbt-buildinfo/blob/master/LICENSE")),
    scalacOptions ++= Seq("-Xlint", "-Xfatal-warnings"),
    check := {
      val f = (sourceManaged in Compile).value / "sbt-buildinfo" / ("%s.scala" format "BuildInfo")
      val lines = scala.io.Source.fromFile(f).getLines.toList
      lines match {
        case  """// $COVERAGE-OFF$""" ::
              """package hello""" ::
              """""" ::
              """import scala.Predef._""" ::
              """""" ::
              """/** This object was generated by sbt-buildinfo. */""" ::
              """private[hello] case object BuildInfo extends TestTrait1 with TestTrait2 with TestTrait3 {""" ::
              """  /** The value is "helloworld". */""" ::
              """  val name: String = "helloworld"""" ::
              """  /** The value is "2.12.12". */""" ::
              """  val scalaVersion: String = "2.12.12"""" ::
              """  override val toString: String = {""" ::
              """    "name: %s, scalaVersion: %s".format(""" ::
              """      name, scalaVersion""" ::
              """    )""" ::
              """  }""" ::
              """  val toMap: Map[String, Any] = Map[String, Any](""" ::
              """    "name" -> name,""" ::
              """    "scalaVersion" -> scalaVersion)""" ::
              """""" ::
              """  private def quote(x: Any): String = "\"" + x + "\""""" ::
              """  private def toJsonValue(value: Any): String = {""" ::
              """    value match {""" ::
              """      case elem: Seq[_] => elem.map(toJsonValue).mkString("[", ",", "]")""" ::
              """      case elem: Option[_] => elem.map(toJsonValue).getOrElse("null")""" ::
              """      case elem: Map[_, Any] => elem.map {""" ::
              """        case (k, v) => toJsonValue(k.toString) + ":" + toJsonValue(v)""" ::
              """      }.mkString("{", ", ", "}")""" ::
              """      case d: Double => d.toString""" ::
              """      case f: Float => f.toString""" ::
              """      case l: Long => l.toString""" ::
              """      case i: Int => i.toString""" ::
              """      case s: Short => s.toString""" ::
              """      case bool: Boolean => bool.toString""" ::
              """      case str: String => quote(str)""" ::
              """      case other => quote(other.toString)""" ::
              """    }""" ::
              """  }""" ::
              """""" ::
              """  val toJson: String = toJsonValue(toMap)""" ::
              """}""" ::
              """// $COVERAGE-ON$""" ::
              Nil =>
        case _    => sys.error("unexpected output: \n" + lines.mkString("\n"))
      }
      ()
    }
  )
