lazy val check = taskKey[Unit]("check")

ThisBuild / scalaVersion := "2.12.21"
ThisBuild / organization := "com.example"
ThisBuild / version := "0.1"
ThisBuild / homepage := Some(url("http://example.com"))
ThisBuild / licenses := Seq("MIT License" -> url("https://github.com/sbt/sbt-buildinfo/blob/master/LICENSE"))

lazy val root = (project in file("."))
  .enablePlugins(BuildInfoPlugin, SbtPlugin)
  .settings(
    name := "helloworld",
    scalacOptions ++= Seq("-Xlint", "-Xfatal-warnings", "-Yno-imports"),
    buildInfoKeys ++= Seq[BuildInfoKey](name, organization, version, scalaVersion,
      libraryDependencies,
      (Test / libraryDependencies: SettingKey[Seq[ModuleID]])),
    buildInfoKeys += BuildInfoKey(resolvers),
    buildInfoPackage := "hello",
    buildInfoOptions := Seq(BuildInfoOption.ImportScalaPredef),
    resolvers ++= Seq("Sonatype Public" at "https://oss.sonatype.org/content/groups/public"),
    check := {
      val f = (Compile / sourceManaged).value / "sbt-buildinfo" / ("%s.scala" format "BuildInfo")
      val lines = scala.io.Source.fromFile(f).getLines.toList
      lines match {
        case """// $COVERAGE-OFF$""" ::
             """package hello""" ::
             """""" ::
             """import scala.Predef._""" ::
             """""" ::
             """/** This object was generated by sbt-buildinfo. */""" ::
             """case object BuildInfo {""" ::
             """  /** The value is "helloworld". */""" ::
             """  val name: String = "helloworld"""" ::
             """  /** The value is "0.1". */""" ::
             """  val version: String = "0.1"""" ::
             """  /** The value is "2.12.21". */""" ::
             """  val scalaVersion: String = "2.12.21"""" ::
             sbtVersionComment ::
             sbtVersionCode ::
             """  /** The value is "com.example". */""" ::
             """  val organization: String = "com.example"""" ::
             depsComment ::
             depsCode ::
             testDepsComment ::
             testDepsCode ::
             """  /** The value is scala.collection.immutable.Seq("Sonatype Public: https://oss.sonatype.org/content/groups/public"). */""" ::
             """  val resolvers: scala.collection.immutable.Seq[String] = scala.collection.immutable.Seq("Sonatype Public: https://oss.sonatype.org/content/groups/public")""" ::
             """  override val toString: String = {""" ::
             """    import _root_.scala.StringContext""" ::
             """    s"name: ${name}, version: ${version}, scalaVersion: ${scalaVersion}, sbtVersion: ${sbtVersion}, organization: ${organization}, libraryDependencies: ${libraryDependencies}, test_libraryDependencies: ${test_libraryDependencies}, resolvers: ${resolvers}"""" ::
             """  }""" ::
             """}""" ::
             """// $COVERAGE-ON$""" :: Nil =>
        case _ =>
          sys.error("unexpected output: \n" + lines.mkString("\n"))
      }
      ()
    }
  )
