name: CI
on:
  pull_request:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            java: 17
            distribution: zulu
            scala: 3.x
          - os: ubuntu-latest
            java: 17
            distribution: zulu
            scala: 3.x
          - os: ubuntu-latest
            java: 8
            distribution: zulu
            scala: 2.12.x
    runs-on: ${{ matrix.os }}
    env:
      JAVA_OPTS: -Xms800M -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=128M -Dfile.encoding=UTF-8
      JVM_OPTS: -Xms800M -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=128M -Dfile.encoding=UTF-8
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-java@v6
      with:
        distribution: "${{ matrix.distribution }}"
        java-version: "${{ matrix.java }}"
        cache: "sbt"
    - uses: sbt/setup-sbt@v1
    - shell: bash
      run: |
        sbt -v clean "++${{ matrix.scala }}" compile || true
        sleep 1
        sbt -v "++${{ matrix.scala }}" test scripted
